### PR TITLE
Amqp config

### PR DESCRIPTION
**Pull request by kaladinlight**
- Create an amqp config interface that contains the connection and the configuration for both the exchange and queue.
- Unbind and delete queue when disposing subscriber.
- Use random string for routing key when asyncIterator `eventName` is `fanout`. This allows many queues to be bound to the fanout exchange and managed properly when unsubscribing.
- Add some try/catches for error handling and some additional logs.
- Use async/await for easier readability.
- Update tests.

I mainly implemented these changes because we were using a fanout exchange vs the topic exchange this was setup to work with. I haven't done any testing against the topic exchange setup outside of the test suites you had made. Let me know what you think of if you have any questions. Thanks!

### CODE REVIEW

**Comment by matthewhall-ca** [comment]
@kaladinlight @chdanielmueller any chance of this getting merged? It's a great improvement - we need to tweak durable settings

**Comment by gad0lin** [comment]
it would be great to get it in, I need same functionality, I can help with resolving merge conflicts if it's of any use.

**Comment by kaladinlight** [comment]
I went ahead and fixed the merge conflicts and verified all of the tests are still passing if we can try and get this in due to the recent interest. @chdanielmueller

**Comment by gad0lin** [comment]
Thanks for updating the pr. I have loaded the PR and it works. Will use my fork for time being.

1.  I have pushed PR to my fork: https://github.com/gad0lin/graphql-amqp-subscriptions

2. Modified .npm_ignore in fork gad0lin/graphql-amqp-subscriptions and removed src so that I can use and build package locally (nothing needed on the user side)

3. In my graphql project.

a)  Added new dependency to point to above with:
`
npm install gad0lin/graphql-amqp-subscriptions
`

b)  Added entry to package.json under scripts:
`
    "postinstall": "cd node_modules/graphql-amqp-subscriptions; npm install; npm run build",
`
5. Run my project  and subscription work.

image

**Comment by chdanielmueller** [comment]
Hi @kaladinlight, @matthewhall-ca, @gad0lin 

I did some changes to the code to be more backwards compatible.
Please check blockrange/graphql-amqp-subscriptions#2 and review it.

Thanks,
Daniel

**Pull request merged**
